# Generated by Django 3.1.4 on 2020-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('models_before', models.IntegerField()),
            ],
        ),
    ]
