# Generated by Django 3.1.4 on 2020-12-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_registered_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.CharField(max_length=20),
        ),
    ]
